global_costmap:
  global_frame: /odom   # Because we don't have a map to load in, we use the odom frame as our global frame (rather than /map)
  robot_base_frame: base_link
  update_frequency: 5.0
  rolling_window: true  # Set this to true bc static map == false (this makes setting 2D nav goals in rviz work)
  static_map: false     # Not supplying a static map
  